[package]
name = "iced-optional-element-shim"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["iced", "util"]
repository = "https://github.com/hiteshjasani/iced-optional-element-shim"

[dependencies]
iced = { version = "0.13.1", features = ["advanced"] }
